FROM alpine:3.17

RUN apk add --update \
ruby \
ruby-dev \
ruby-io-console \
ruby-json \
ruby-bigdecimal \
bash \
sqlite \
sqlite-dev \
openssl-dev \
build-base

RUN gem install mailcatcher --no-document

# smtp port
EXPOSE 80 25

CMD ["mailcatcher", "-f", "--ip", "0.0.0.0", "--smtp-port", "25", "--http-port", "80"]
